require "bundler/setup"
require "rake/testtask"

APP_RAKEFILE = File.expand_path("../demo/Rakefile", __dir__)
load "rails/tasks/engine.rake" if File.exist?(APP_RAKEFILE)

Rake::TestTask.new(:test) do |t|
  t.libs    << "test"
  t.pattern = "test/**/*_test.rb"
end

task default: :test
